REM INSERTING into URSUS.MAPS
SET DEFINE OFF;
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('sqlnav','PACKAGE','PAK');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('sqlnav','PACKAGE BODY','PLS');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('sqlnav','VIEW','VIW');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('sqlnav','TABLE','TAB');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('sqlnav','TYPE','TYP');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('sqlnav','TYPE BODY','TPB');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('sqlnav','PROCEDURE','SQL');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('sqlnav','FUNCTION','SQL');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('sqlnav','INDEX','IDX');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('sqlnav','SEQUENCE','SEQ');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('sqlnav','JOB','JOB');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('sqlnav','TRIGGER','TRI');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('ursus','PACKAGE','PAK');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('ursus','PACKAGE BODY','PLS');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('ursus','VIEW','VIW');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('ursus','TABLE','TAB');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('ursus','TYPE','TYP');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('ursus','TYPE BODY','TPB');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('ursus','PROCEDURE','PRC');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('ursus','FUNCTION','FUN');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('ursus','INDEX','IDX');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('ursus','SEQUENCE','SEQ');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('ursus','JOB','JOB');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('ursus','TRIGGER','TRI');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('ursus','MATERIALIZED VIEW','MVW');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('ursus','SNAPSHOT','MVW');
