REM INSERTING into URSUS.MAPS
SET DEFINE OFF;
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('sqlnav','PACKAGE','PAK');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('sqlnav','PACKAGE BODY','PLS');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('sqlnav','VIEW','VIW');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('sqlnav','TABLE','TAB');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('sqlnav','TYPE','TYP');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('sqlnav','TYPE BODY','TPB');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('sqlnav','PROCEDURE','SQL');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('sqlnav','FUNCTION','SQL');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('sqlnav','INDEX','IDX');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('sqlnav','SEQUENCE','SEQ');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('sqlnav','JOB','JOB');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('sqlnav','TRIGGER','TRI');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('sqlnav','OBJECT PRIVILEGE','grants.SQL');

Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('ursus','PACKAGE','PAK');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('ursus','PACKAGE BODY','PLS');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('ursus','VIEW','VIW');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('ursus','TABLE','TAB');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('ursus','TYPE','TYP');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('ursus','TYPE BODY','TPB');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('ursus','PROCEDURE','PRC');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('ursus','FUNCTION','FUN');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('ursus','INDEX','IDX');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('ursus','SEQUENCE','SEQ');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('ursus','JOB','JOB');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('ursus','TRIGGER','TRI');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('ursus','MATERIALIZED VIEW','MVW');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('ursus','SNAPSHOT','MVW');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('ursus','OBJECT PRIVILEGE','grants.SQL');

Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('liquibase','PACKAGE','package');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('liquibase','PACKAGE BODY','packagebody');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('liquibase','VIEW','view');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('liquibase','TABLE','table');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('liquibase','TYPE','type');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('liquibase','TYPE BODY','typebody');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('liquibase','PROCEDURE','procedure');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('liquibase','FUNCTION','function');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('liquibase','INDEX','index');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('liquibase','SEQUENCE','sequence');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('liquibase','JOB','job');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('liquibase','TRIGGER','trigger');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('liquibase','MATERIALIZED VIEW','matview');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('liquibase','SNAPSHOT','matview');
Insert into URSUS.MAPS (MAP_NAME,KEY,VALUE) values ('liquibase','OBJECT PRIVILEGE','grants');
commit;